  name = "v20251104"
  main = "_worker.js"
  compatibility_date = "2025-11-04"
  keep_vars = true

  [vars]
  ADMIN = "123456"

  [[kv_namespaces]]
  binding = "KV"
  id = "3c79a53b445b45df86dba3ba53e67831"
